# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='publication_date',
        ),
    ]
