# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180222_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Author Name'),
        ),
    ]
