# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180222_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the title of the Post', unique=True),
        ),
    ]
